# Generated by Django 4.2.2 on 2023-07-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0002_alter_worker_position")]

    operations = [
        migrations.AlterModelOptions(name="task", options={"ordering": ["deadline"]}),
        migrations.AlterModelOptions(name="worker", options={"ordering": ["username"]}),
    ]
